### ISSUE TITLE
bot is in my server but does not respond to commands.

### ISSUE THREAD

**Issue by kireita** [TehNut/AniSchedule#10]
Hey, i was able to have it join my server, and gave it an administrator rol but unfortunatly it does not respond to anything i do:
![image](https://user-images.githubusercontent.com/25864917/98421147-00258780-2089-11eb-9d85-4bc84b1d7501.png)
![image](https://user-images.githubusercontent.com/25864917/98421213-22b7a080-2089-11eb-92e8-b44ba1c454f9.png)
![image](https://user-images.githubusercontent.com/25864917/98421288-4844aa00-2089-11eb-9204-785e593baee5.png)

can you guys help me with this? i dont know what im doing wrong

**Comment by TehNut** [comment]
Ah, sorry, I forgot to update that part of the readme. The `.env` file only dictates the token, now. In 2.0, the bot was rewritten to better support being in multiple servers.

To configure the bot like you have there, run `?asprefix ?an` and `?anpermission ANY`. Note the second one is `?an`.

I'll update the readme to reflect this.

**Comment by kireita** [comment]
Thanks mate i have it working now :D
