### ISSUE TITLE
?aswatching breaks when an anime ends

### ISSUE THREAD

**Issue by huntrshado** [TehNut/AniSchedule#11]
It seems that since the requested Airing Date in the ?aswatching command was added, now whenever an anime ends, it breaks the ?aswatching command until you remove the animes that ended. Hasn't been a big deal, but the annoying part is figuring out what animes ended that were still on the list. Easiest way has been to go into the file where that info is stored, but that can obviously be a hassle.

Can it be changed to automatically remove an anime that does not have a next airing date?

**Comment by TehNut** [comment]
Odd, it *should* be getting removed when the final episode announcement is made...

https://github.com/TehNut/AniSchedule/blob/7baf68336db4d5af639a3b6d0b078a94ce3881ed/src/AniSchedule.ts#L76-L77

I'll add a check for `nextAiringEpisode`, though.

**Comment by TehNut** [comment]
This is now fixed in 2.0.3 
https://github.com/TehNut/AniSchedule/releases/tag/2.0.3
