### ISSUE TITLE
Clone??

### ISSUE THREAD

**Issue by uditrao04** [TehNut/AniSchedule#20]
What does it mean by "clone"??

git clone https://github.com/TehNut/AniSchedule.git #
git clone https://github.com/TehNut/AniSchedule.git #
    ^^^^^

Uncaught SyntaxError: Unexpected identifier

pls help me

**Comment by TehNut** [comment]
Sorry, I'm not really sure what you mean. It's telling you to run `git clone https://github.com/TehNut/AniSchedule.git` in your terminal.
