### ISSUE TITLE
Error when running on Windows 10 (Discord token is invalid)

### ISSUE THREAD

**Issue by ld3z** [TehNut/AniSchedule#29]
### (OS is Windows 10)
Everything installs correctly and I have a .env file in the root where the README is with the correct bot token.

But I get an "Error occurred An invalid token was provided".
First image is terminal:
![cmd_yVjg1HPzun](https://user-images.githubusercontent.com/42660576/177090060-a2c0f8bf-6f43-412d-8ece-9e351cb26c84.png)
Next image is what's inside my .env file:
![notepad++_Hw3oIDGADM](https://user-images.githubusercontent.com/42660576/177090195-c979b438-01fd-4abf-a77b-ecb33d4f75ba.png)
Last image is where the .env file is:
![explorer_szEfnqgtsE](https://user-images.githubusercontent.com/42660576/177090634-0ea2a09f-1ba2-4880-8e33-b3a3daa374c0.png)
Should be called bot.env

**Comment by nosut** [comment]
In your .env try using 
BOT_TOKEN= instead of TOKEN=

Also change your bot token asap. If that token is still active and the bot in your server someone could screw you over.

**Comment by ld3z** [comment]
I figured it out but forgot to close this. Sorry! 😅
