### ISSUE TITLE
[Request] Anime search by name

### ISSUE THREAD

**Issue by RootAndroid58** [TehNut/AniSchedule#3]
as you may know we have to insert the anime link instead simply search for anime 
ex. your prefix is .
.watch boruto naruto next generations 
something like that instead of  
.watch https://myanimelist.net/anime/34566/Boruto__Naruto_Next_Generations
by the way bot is best just needed that for making it prefect

**Comment by TehNut** [comment]
There really isn't a good way to do this since names aren't 1:1. You can search one name and get a completely different series.
