### ISSUE TITLE
[Request] Option to include multiple anime IDs

### ISSUE THREAD

**Issue by zerdrag99** [TehNut/AniSchedule#4]
It is quite a pain to include either the IDs or the links themselves multiple times to add them to the watching list. It would be great if either there were an option to include multiple IDs or the entire season altogether (this could be helpful for anime related servers).

The bot itself is pretty good and has a neat display. Hope the above request can be considered.

**Comment by TehNut** [comment]
Sure, that shouldn't be too much trouble to add

**Comment by TehNut** [comment]
https://github.com/TehNut/AniSchedule/releases/tag/1.1.5
