### ISSUE TITLE
Issue with starting it

### ISSUE THREAD

**Issue by BanMeNerd** [TehNut/AniSchedule#9]
According to npm `node dist/AniSchedule.js` is failing.
[npm-debug.log](https://github.com/TehNut/AniSchedule/files/5418513/npm-debug.log)

**Comment by TehNut** [comment]
> `using node@v4.2.6`

I would hazard a guess that it's because of this. Node 4.2.6 is over 4 years old and isn't even considered LTS anymore. The latest LTS version is 10.x.

Try updating node and running it again

**Comment by BanMeNerd** [comment]
I get this error still.
`> anischedule@2.0.2 start /root/AniSchedule
> node dist/AniSchedule.js

node:internal/modules/cjs/loader:903
  throw err;
  ^

Error: Cannot find module '/root/AniSchedule/dist/AniSchedule.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:72:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

npm ERR! Linux 4.4.0-186-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! anischedule@2.0.2 start: `node dist/AniSchedule.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the anischedule@2.0.2 start script 'node dist/AniSchedule.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the anischedule package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/AniSchedule.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs anischedule
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls anischedule
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/AniSchedule/npm-debug.log`

**Comment by TehNut** [comment]
Just to be sure, you *did* run `npm build` first, right?

**Comment by BanMeNerd** [comment]
Npm install then npm build yeah.

**Comment by mattthw** [comment]
@BanMeNerd did you resolve the issue? I am using the latest node and it hangs at 
```
             ├─9795 npm start
             ├─9806 sh -c node dist/AniSchedule.js
             └─9807 node dist/AniSchedule.js
```
